# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: uber/android-build-environment

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - ./gradlew build