# You can use a Docker image from Docker Hub or your own container
# registry for your build environment. 
image: jacekmarchwicki/android

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - echo "Starting"
          - ls /opt/atlassian/bitbucketci/agent/build
          - /opt/atlassian/bitbucketci/agent/build/gradlew build